name: Daily Java Solution Push

on:
  workflow_dispatch:
  schedule:
    # Runs every day at 12:00 UTC (adjust if you want)
    - cron: '30 10 * * *'  # Runs every day at 10:30 UTC (4:00 PM IST)

jobs:
  daily_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run auto_push script
        run: python3 auto_push.py

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
